/**
 * Room Readiness Command Center — AI Supervisor (Health)
 *
 * INTEGRATION POINTS (for production):
 * - Header search: would call Bed Mgmt / room search API or agent.
 * - KPIs: would come from analytics/warehouse or real-time aggregation service.
 * - Now Queue: would be driven by an orchestration layer (agent/scheduler) that
 *   consumes Bed Mgmt, EVS, CMMS, Patient Flow and outputs prioritized list.
 * - Alerts: would be generated by rules engine or agent from same sources.
 * - Data Health: would reflect actual integration health (e.g. last successful sync).
 * - Action Drawer actions: would trigger workflows (notify Bed Manager, create
 *   CMMS hold, escalate to EVS/Maintenance) via workflow API or agent tool calls.
 * - Pilot Mode toggle: would gate whether AI can execute automated actions vs.
 *   recommend-only; stored in user/session or feature flag.
 */

import { useMemo, useState, useCallback } from 'react'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { TooltipProvider } from '@/components/ui/tooltip'
import { KPIStatCard } from '@/components/KPIStatCard'
import { RoomCard } from '@/components/RoomCard'
import { AlertsPanel } from '@/components/AlertsPanel'
import { DataHealthPanel } from '@/components/DataHealthPanel'
import { ActionDrawer } from '@/components/ActionDrawer'
import { Chatbot } from '@/components/Chatbot'
import { Toast } from '@/components/Toast'
import type { ChatbotAction } from '@/components/Chatbot'
import {
  mockRooms,
  mockAlerts,
  mockKPIs,
  getInitialDataHealth,
} from '@/data/mockData'
import type { Room, DataHealthItem, BlockerType } from '@/types'
import { Search, User, Sparkles, Undo2, X } from 'lucide-react'

const UNITS = ['All units', '4 West', '3 East', '5 North'] as const
const STATUS_OPTIONS = [
  'All statuses',
  'Ready',
  'Cleaning',
  'Blocked',
  'Unknown',
] as const

function applyDegradedMode(
  rooms: Room[],
  dataHealth: DataHealthItem[]
): Room[] {
  const maintenanceStale = dataHealth.some(
    (d) => d.system === 'Maintenance CMMS' && d.status === 'stale'
  )
  if (!maintenanceStale) return rooms
  // When Maintenance CMMS is stale, rooms with maintenance-related blockers
  // get those blockers shown as "Unknown" (we mask them for display).
  return rooms.map((r) => {
    const maintenanceBlockers = [
      'HVAC work order',
      'Plumbing work order',
      'Maintenance hold',
    ]
    const hasMaintenanceBlocker = r.blockers.some((b) =>
      maintenanceBlockers.includes(b)
    )
    if (!hasMaintenanceBlocker) return r
    const otherBlockers = r.blockers.filter(
      (b) => !maintenanceBlockers.includes(b)
    )
    const maskedBlockers: BlockerType[] =
      otherBlockers.length > 0
        ? [...otherBlockers, 'Unknown (maintenance)']
        : ['Unknown (maintenance)']
    return { ...r, blockers: maskedBlockers }
  })
}

export interface RecentAiAction {
  id: string
  action: string
  roomId: string
}

export default function App() {
  const [pilotMode, setPilotMode] = useState(true)
  const [pilotTipDismissed, setPilotTipDismissed] = useState(false)
  const [showPilotOffConfirm, setShowPilotOffConfirm] = useState(false)
  const [recentAiActions, setRecentAiActions] = useState<RecentAiAction[]>([])
  const [searchQuery, setSearchQuery] = useState('')
  const [unitFilter, setUnitFilter] = useState<string>(UNITS[0])
  const [statusFilter, setStatusFilter] = useState<string>(STATUS_OPTIONS[0])
  const [showOnlyBlocked, setShowOnlyBlocked] = useState(false)
  const [selectedRoom, setSelectedRoom] = useState<Room | null>(null)
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [toastMessage, setToastMessage] = useState('')
  const [toastVisible, setToastVisible] = useState(false)
  const [requireConfirmation, setRequireConfirmation] = useState(true)
  const [dataHealth, setDataHealth] = useState<DataHealthItem[]>(
    getInitialDataHealth
  )
  const [activeTab, setActiveTab] = useState('alerts')

  const showToast = useCallback((msg: string) => {
    setToastMessage(msg)
    setToastVisible(true)
  }, [])

  const handleActionsClick = useCallback((room: Room) => {
    setSelectedRoom(room)
    setDrawerOpen(true)
  }, [])

  const handleDrawerAction = useCallback(
    (action: string) => {
      const msg =
        action === 'Notify Bed Manager'
          ? 'Notification sent'
          : action === 'Create Maintenance Hold'
            ? 'Hold created (simulated)'
            : action === 'Escalate to Maintenance'
              ? 'Escalation sent (simulated)'
              : action === 'Reprioritize EVS'
                ? 'EVS reprioritized (simulated)'
                : `${action} (simulated)`
      showToast(msg)
    },
    [showToast]
  )

  const handlePilotModeChange = useCallback(
    (checked: boolean) => {
      if (checked) {
        setPilotMode(true)
      } else {
        setShowPilotOffConfirm(true)
      }
    },
    []
  )

  const confirmPilotModeOff = useCallback(() => {
    setPilotMode(false)
    setShowPilotOffConfirm(false)
    const simulated: RecentAiAction = {
      id: crypto.randomUUID(),
      action: 'Notified Bed Manager',
      roomId: '4W-412B',
    }
    setRecentAiActions((prev) => [simulated, ...prev])
    showToast(
      'AI took an action: Notified Bed Manager for 4W-412B. You can undo below.'
    )
  }, [showToast])

  const undoAiAction = useCallback((id: string) => {
    setRecentAiActions((prev) => prev.filter((a) => a.id !== id))
    showToast('Action undone.')
  }, [showToast])

  const toggleMaintenanceStale = useCallback(() => {
    setDataHealth((prev) =>
      prev.map((d) =>
        d.system === 'Maintenance CMMS'
          ? {
              ...d,
              status: d.status === 'stale' ? ('ok' as const) : ('stale' as const),
              degradedReason:
                d.status === 'stale'
                  ? undefined
                  : 'Simulated: integration down. Blockers relying on maintenance show as Unknown.',
            }
          : d
      )
    )
  }, [])

  const roomsWithDegraded = useMemo(
    () => applyDegradedMode(mockRooms, dataHealth),
    [dataHealth]
  )

  const handleChatbotAction = useCallback(
    (action: ChatbotAction) => {
      switch (action.type) {
        case 'reprioritizeEvs':
          if (action.payload) {
            setUnitFilter(action.payload)
            const aiAction = {
              id: crypto.randomUUID(),
              action: `Reprioritized EVS for ${action.payload}`,
              roomId: action.payload,
            }
            setRecentAiActions((prev) => [aiAction, ...prev])
            showToast(`EVS crews reprioritized to ${action.payload}. Staff notified.`)
          }
          break
        case 'escalateMaintenance':
          if (action.payload) {
            setUnitFilter(action.payload)
            const aiAction = {
              id: crypto.randomUUID(),
              action: `Escalated maintenance for ${action.payload}`,
              roomId: action.payload,
            }
            setRecentAiActions((prev) => [aiAction, ...prev])
            showToast(`Maintenance escalated to prioritize ${action.payload} hardware.`)
          }
          break
        case 'informStaff':
          if (action.payload) {
            setUnitFilter(action.payload)
            const aiAction = {
              id: crypto.randomUUID(),
              action: `Informed staff to focus on ${action.payload}`,
              roomId: action.payload,
            }
            setRecentAiActions((prev) => [aiAction, ...prev])
            showToast(`Staff informed: Focus on cleaning ${action.payload} rooms.`)
          }
          break
        case 'setUnitFilter':
          if (action.payload) setUnitFilter(action.payload)
          break
        case 'setStatusFilter':
          if (action.payload) {
            setShowOnlyBlocked(false)
            setStatusFilter(action.payload)
          }
          break
        case 'setShowOnlyBlocked':
          setStatusFilter('All statuses')
          setShowOnlyBlocked(true)
          break
        case 'setSearchQuery':
          if (action.payload) setSearchQuery(action.payload)
          break
        case 'resetFilters':
          setUnitFilter(UNITS[0])
          setStatusFilter(STATUS_OPTIONS[0])
          setShowOnlyBlocked(false)
          setSearchQuery('')
          break
        case 'openRoom':
          if (action.payload) {
            const room = roomsWithDegraded.find(
              (r) =>
                r.roomId.toLowerCase().includes(action.payload!.toLowerCase()) ||
                action.payload!.toLowerCase().includes(r.roomId.toLowerCase())
            )
            if (room) {
              setSelectedRoom(room)
              setDrawerOpen(true)
            }
          }
          break
        case 'switchTab':
          if (action.payload) setActiveTab(action.payload)
          break
        case 'showHelp':
          break // Chatbot handles response itself
      }
    },
    [roomsWithDegraded, showToast]
  )

  const filteredRooms = useMemo(() => {
    let list = roomsWithDegraded
    if (unitFilter !== 'All units') {
      list = list.filter((r) => r.unit === unitFilter)
    }
    if (statusFilter !== 'All statuses') {
      list = list.filter((r) => r.status === statusFilter)
    }
    if (showOnlyBlocked) {
      list = list.filter((r) => r.status === 'Blocked')
    }
    const q = searchQuery.trim().toLowerCase()
    if (q) {
      list = list.filter(
        (r) =>
          r.roomId.toLowerCase().includes(q) ||
          r.unit.toLowerCase().includes(q)
      )
    }
    return list
  }, [roomsWithDegraded, unitFilter, statusFilter, showOnlyBlocked, searchQuery])

  return (
    <TooltipProvider>
      <div className="min-h-screen bg-background font-sans text-text antialiased">
        {/* Header */}
        <header className="sticky top-0 z-40 border-b border-slate-200 bg-surface">
          <div className="mx-auto flex h-14 max-w-[1600px] items-center justify-between gap-4 px-4">
            <div className="flex items-center gap-3">
              {/* Your Health logo; height constrained so excess white doesn’t dominate */}
              <img
                src="/health-logo.png"
                alt="Health"
                className="h-9 w-auto max-w-[180px] object-contain object-left"
              />
              <span className="text-sm text-text-muted">AI Supervisor</span>
            </div>
            <div className="flex flex-1 max-w-md items-center gap-2 rounded-lg border border-slate-200 bg-background px-3 py-1.5">
              <Search className="h-4 w-4 shrink-0 text-text-muted" />
              <Input
                placeholder="Search room number, unit..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="border-0 bg-transparent shadow-none focus-visible:ring-0"
              />
            </div>
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <span className="text-sm text-text-muted">Pilot Mode</span>
                <Switch
                  checked={pilotMode}
                  onCheckedChange={handlePilotModeChange}
                  aria-label="Pilot mode"
                />
              </div>
              <div
                className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-200 text-text-muted"
                aria-hidden
              >
                <User className="h-4 w-4" />
              </div>
            </div>
          </div>
        </header>

        {/* Floating popup hint when Pilot Mode is on — front layer, dismissible */}
        {pilotMode && !pilotTipDismissed && (
          <div
            className="fixed right-4 top-14 z-[100] flex max-w-[280px] animate-bounce items-start gap-2 rounded-lg border border-primary/30 bg-surface px-3 py-2.5 shadow-lg"
            role="status"
            aria-live="polite"
          >
            <Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
            <div className="min-w-0 flex-1 text-sm text-text">
              <p>Want to let the AI handle changes?</p>
              <p className="text-text-muted">
                Turn off Pilot Mode to enable autonomous actions.
              </p>
            </div>
            <button
              type="button"
              onClick={() => setPilotTipDismissed(true)}
              className="shrink-0 rounded p-1 text-text-muted hover:bg-slate-100 hover:text-text focus:outline-none focus:ring-2 focus:ring-primary"
              aria-label="Dismiss hint"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        )}

        {/* Recent AI actions — showcase agentic workflow + undo (chatbot or autonomous) */}
        {recentAiActions.length > 0 && (
          <div className="border-b border-slate-200 bg-primary/5 px-4 py-2">
            <div className="mx-auto flex max-w-[1600px] flex-wrap items-center justify-between gap-2">
              <span className="text-sm font-medium text-text">
                Latest AI action:{' '}
                <span className="text-primary-dark">
                  {recentAiActions[0].action} for {recentAiActions[0].roomId}
                </span>
              </span>
              <Button
                variant="outline"
                size="sm"
                onClick={() => undoAiAction(recentAiActions[0].id)}
                className="gap-1.5"
              >
                <Undo2 className="h-3.5 w-3.5" />
                Undo
              </Button>
            </div>
          </div>
        )}

        <main className="mx-auto max-w-[1600px] space-y-6 p-4">
          {/* KPI strip */}
          <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {mockKPIs.map((kpi) => (
              <KPIStatCard key={kpi.label} metric={kpi} />
            ))}
          </section>

          {/* Healthops Agent — full-width below KPIs */}
          <Chatbot
            onAction={handleChatbotAction}
            useRealAi={false}
          />

          {/* Filters */}
          <section className="flex flex-wrap items-center gap-4 rounded-lg border border-slate-200 bg-surface p-3">
            <label className="flex items-center gap-2 text-sm text-text-muted">
              Unit
              <select
                value={unitFilter}
                onChange={(e) => setUnitFilter(e.target.value)}
                className="rounded-md border border-slate-200 bg-background px-2 py-1.5 text-sm text-text focus:outline-none focus:ring-2 focus:ring-primary"
              >
                {UNITS.map((u) => (
                  <option key={u} value={u}>
                    {u}
                  </option>
                ))}
              </select>
            </label>
            <label className="flex items-center gap-2 text-sm text-text-muted">
              Status
              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="rounded-md border border-slate-200 bg-background px-2 py-1.5 text-sm text-text focus:outline-none focus:ring-2 focus:ring-primary"
              >
                {STATUS_OPTIONS.map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
            </label>
            <label className="flex items-center gap-2 text-sm text-text-muted">
              <input
                type="checkbox"
                checked={showOnlyBlocked}
                onChange={(e) => setShowOnlyBlocked(e.target.checked)}
                className="h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary"
              />
              Show only blocked
            </label>
          </section>

          {/* Main content: Now Queue (left) + Tabs (right) */}
          <section className="grid grid-cols-1 gap-6 lg:grid-cols-3">
            <div className="lg:col-span-2">
              <h2 className="mb-3 text-lg font-semibold text-text">
                Now Queue
              </h2>
              <div className="space-y-3">
                {filteredRooms.length === 0 ? (
                  <p className="rounded-lg border border-slate-200 bg-surface p-4 text-sm text-text-muted">
                    No rooms match the current filters.
                  </p>
                ) : (
                  filteredRooms.map((room) => (
                    <RoomCard
                      key={room.id}
                      room={room}
                      onActionsClick={handleActionsClick}
                    />
                  ))
                )}
              </div>
            </div>
            <div>
              <Tabs
                value={activeTab}
                onValueChange={setActiveTab}
                className="w-full"
              >
                <TabsList className="w-full">
                  <TabsTrigger value="alerts" className="flex-1">
                    Alerts
                  </TabsTrigger>
                  <TabsTrigger value="data-health" className="flex-1">
                    Data Health
                  </TabsTrigger>
                </TabsList>
                <TabsContent value="alerts" className="mt-3">
                  <AlertsPanel
                    alerts={mockAlerts}
                    onRecommendedStep={(a) =>
                      showToast(`Recommended: ${a.recommendedStep}`)
                    }
                  />
                </TabsContent>
                <TabsContent value="data-health" className="mt-3">
                  <DataHealthPanel
                    items={dataHealth}
                    onToggleStale={toggleMaintenanceStale}
                    staleToggleSystem="Maintenance CMMS"
                  />
                </TabsContent>
              </Tabs>
            </div>
          </section>
        </main>

        <ActionDrawer
          room={selectedRoom}
          open={drawerOpen}
          onOpenChange={setDrawerOpen}
          onAction={handleDrawerAction}
          requireConfirmation={requireConfirmation}
          onRequireConfirmationChange={setRequireConfirmation}
        />

        {/* Confirm before turning off Pilot Mode */}
        <Dialog open={showPilotOffConfirm} onOpenChange={setShowPilotOffConfirm}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Enable autonomous AI?</DialogTitle>
              <DialogDescription>
                AI will make decisions and can take actions on your behalf (e.g.
                notify Bed Manager, reprioritize EVS, create maintenance holds).
                You can undo recent actions in the bar below the header.
              </DialogDescription>
            </DialogHeader>
            <DialogFooter className="mt-4 gap-2 sm:gap-0">
              <Button
                variant="outline"
                onClick={() => setShowPilotOffConfirm(false)}
              >
                Cancel
              </Button>
              <Button onClick={confirmPilotModeOff}>Enable</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        <Toast
          message={toastMessage}
          visible={toastVisible}
          onDismiss={() => setToastVisible(false)}
        />
      </div>
    </TooltipProvider>
  )
}
